CREATE DATABASE LIBRARY4;
USE LIBRARY4;

CREATE TABLE ADMIN(
USER_ID VARCHAR(50) PRIMARY KEY,
NAME VARCHAR(50),
PASSWORD VARCHAR(50),
CONTACT VARCHAR(10));

INSERT INTO ADMIN VALUES ('amin@123','AMIN KUMAR','amin12345678','7654377864');

SELECT * FROM ADMIN;

CREATE TABLE BOOKS(
BOOK_ID VARCHAR(20) PRIMARY KEY,
CATEGORY VARCHAR(50),
NAME VARCHAR(50),
AUTHOR VARCHAR(50),
COPIES INTEGER NOT NULL);

INSERT INTO BOOKS VALUES('B001','DSA','ALGORITHMS MADE EASY','NARSHIMA KARUMANCHI',10);
INSERT INTO BOOKS VALUES('B002', 'OOP', 'OBJECT ORIENTED PROGRAMMING', 'E. BALAGURUSAMY', 15);
INSERT INTO BOOKS VALUES('B003', 'DBMS', 'DATABASE SYSTEM CONCEPTS', 'ABRAHAM SILBERSCHATZ', 12);
INSERT INTO BOOKS VALUES('B004', 'OS', 'OPERATING SYSTEM PRINCIPLES', 'GALVIN', 8);
INSERT INTO BOOKS VALUES('B005', 'CN', 'COMPUTER NETWORKS', 'ANDREW S. TANENBAUM', 20);
INSERT INTO BOOKS VALUES('B006', 'ML', 'PATTERN RECOGNITION AND MACHINE LEARNING', 'CHRISTOPHER BISHOP', 5);
INSERT INTO BOOKS VALUES('B007', 'AI', 'ARTIFICIAL INTELLIGENCE: A MODERN APPROACH', 'STUART RUSSELL', 10);
INSERT INTO BOOKS VALUES('B008', 'SE', 'SOFTWARE ENGINEERING', 'IAN SOMMERVILLE', 18);
INSERT INTO BOOKS VALUES('B009', 'WEB', 'WEB TECHNOLOGIES', 'UJJWAL MAULIK', 12);
INSERT INTO BOOKS VALUES('B010', 'DS', 'DATA SCIENCE FROM SCRATCH', 'JOEL GRUS', 6);

SELECT * FROM BOOKS;

CREATE TABLE STAFFS(
STAFF_ID VARCHAR(10) PRIMARY KEY,
NAME VARCHAR(20),
CONTACT VARCHAR(15));

INSERT INTO STAFFS VALUES('S001','RAGHAV KUMAR',2345676543);
INSERT INTO STAFFS VALUES('S002', 'PRIYA SHARMA', 9876543210);
INSERT INTO STAFFS VALUES('S003', 'AMIT VERMA', 8765432109);
INSERT INTO STAFFS VALUES('S004', 'SNEHA SINGH', 7654321098);
INSERT INTO STAFFS VALUES('S005', 'RAHUL NAIR', 6543210987);
INSERT INTO STAFFS VALUES('S006', 'ANITA JOSHI', 5432109876);
INSERT INTO STAFFS VALUES('S007', 'VIKRAM PATEL', 4321098765);
INSERT INTO STAFFS VALUES('S008', 'DEEPAK GUPTA', 3210987654);
INSERT INTO STAFFS VALUES('S009', 'SONALI ROY', 2109876543);
INSERT INTO STAFFS VALUES('S010', 'MANOJ REDDY', 1098765432);

SELECT * FROM STAFFS;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO users (username, password) VALUES ('admin', 'password123');
 select * from users;
 
 SHOW DATABASES;
